/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/client/v1/account/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a Pro subscription invoice
         * @description Creates a pending subscription and a NowPayments hosted invoice for it.
         *     Redirect the user to `invoice.url` to pay. The subscription activates
         *     through the payment webhook, usually a few minutes after payment.
         *
         *     If the user already has a pending subscription with the same plan, type
         *     and duration, its existing invoice is returned instead of creating a new one.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "plan": "pro",
                     *       "type": "yearly",
                     *       "duration": 1
                     *     }
                     */
                    "application/json": components["schemas"]["SubscribeBody"];
                };
            };
            responses: {
                /** @description Invoice created or reused. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubscribeResponse"];
                    };
                };
                /** @description Validation error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid `oc_token`. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description NowPayments could not create the invoice. */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/account/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current subscription status
         * @description Returns the latest active subscription (which may already be expired,
         *     check `expired`) and every pending subscription with its invoice, so the
         *     client can offer "continue payment" or "cancel".
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Subscription state. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubscriptionStatusResponse"];
                    };
                };
                /** @description Missing or invalid `oc_token`. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/account/subscription/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a pending subscription
         * @description Cancels a pending, unpaid subscription. Paid or active subscriptions cannot
         *     be cancelled here. The NowPayments invoice itself cannot be voided; if it is
         *     paid later anyway, the subscription is activated.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CancelSubscriptionBody"];
                };
            };
            responses: {
                /** @description Subscription cancelled. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CancelSubscriptionResponse"];
                    };
                };
                /** @description Validation error, or the subscription is not pending. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No such subscription for this user. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user and subscription
         * @description Returns the authenticated user's public profile and their latest active subscription.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Authenticated user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PingResponse"];
                    };
                };
                /** @description Missing or invalid `oc_token`. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Returns a JWT. Send it as the `oc_token` header on authenticated requests.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "username": "alice",
                     *       "password": "secret123"
                     *     }
                     */
                    "application/json": components["schemas"]["LoginBody"];
                };
            };
            responses: {
                /** @description Logged in. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Validation error or unknown username. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Wrong password. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign up
         * @description Creates an account with the default `Clipboard` and `Encrypted` folders.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "username": "alice",
                     *       "password": "secret123"
                     *     }
                     */
                    "application/json": components["schemas"]["SignupBody"];
                };
            };
            responses: {
                /** @description Account created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
                /** @description Validation error or username already taken. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/auth/check-username": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check whether a username is taken */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CheckUsernameBody"];
                };
            };
            responses: {
                /** @description Lookup result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckUsernameResponse"];
                    };
                };
                /** @description Invalid username. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List folders
         * @description All folders of the user with their clip counts.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Folders. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Folder"][];
                    };
                };
                /** @description Missing or invalid `oc_token`. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create folder */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "Work"
                     *     }
                     */
                    "application/json": components["schemas"]["CreateFolderBody"];
                };
            };
            responses: {
                /** @description Created folder. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Folder"];
                    };
                };
                /** @description Validation error or a folder with that name already exists. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid `oc_token`. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/folder/{folder}/set-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set folder password
         * @description Stores the password used to encrypt clips in this folder. The client must send the
         *     MD5 hash of the password, never the plain text. Folders with a password cannot be deleted.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Folder slug. */
                    folder: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "password": "5f4dcc3b5aa765d61d8327deb882cf99"
                     *     }
                     */
                    "application/json": components["schemas"]["FolderPasswordBody"];
                };
            };
            responses: {
                /** @description Password set. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
                /** @description Validation error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Folder not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/folder/{folder}/check-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check folder password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Folder slug. */
                    folder: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FolderPasswordBody"];
                };
            };
            responses: {
                /** @description Comparison result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckFolderPasswordResponse"];
                    };
                };
                /** @description Validation error or the folder has no password. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Folder not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/folder/{folder}/enable-public-paste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enable public paste
         * @description Generates a public paste id so anyone can paste into this folder via `/client/v1/clips/paste/{pasteId}`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Folder slug. */
                    folder: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Enabled. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
                /** @description Already enabled. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Folder not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/folder/{folder}/disable-public-paste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable public paste */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Folder slug. */
                    folder: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Disabled. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
                /** @description Not enabled. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Folder not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/folder/{folder}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete folder
         * @description Deletes the folder and every clip in it. The default `clipboard` folder and folders with a password cannot be deleted.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Folder slug. */
                    folder: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
                /** @description Folder is protected or is the default folder. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Folder not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/folders/public/{pasteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Folder by public paste id
         * @description No authentication required. Resolves a public paste id to its folder.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pasteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Folder. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicFolderResponse"];
                    };
                };
                /** @description Paste folder not found or has expired. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/clips/find": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find public-paste clips by id
         * @description No authentication required. Returns clips that were created through public paste,
         *     looked up by their ids. Meant for the paster to see the clips they submitted.
         */
        post: {
            parameters: {
                query?: {
                    page?: number;
                    perPage?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FindClipsBody"];
                };
            };
            responses: {
                /** @description Matching clips, newest first. Empty page when `ids` is empty. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FindClipsResponse"];
                    };
                };
                /** @description Validation error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/clips/paste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Paste a clip
         * @description Creates a clip in a folder. In non-encrypted folders identical content is de-duplicated:
         *     the existing clip's `updatedAt` is touched instead of creating a new one.
         *     Clips pasted into an encrypted folder are stored as-is and flagged `encrypted`, so the
         *     client must encrypt the content before sending it.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "title": "Groceries",
                     *       "content": "milk, eggs",
                     *       "folder": "clipboard"
                     *     }
                     */
                    "application/json": components["schemas"]["PasteBody"];
                };
            };
            responses: {
                /** @description The created or touched clip. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PasteResponse"];
                    };
                };
                /** @description Validation error or unknown folder. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid `oc_token`. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/clips/paste/{pasteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Paste into a shared folder
         * @description No authentication required. Pastes into the folder that owns `pasteId`
         *     (see enable public paste). Identical content is de-duplicated.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pasteId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PublicPasteBody"];
                };
            };
            responses: {
                /** @description The created or existing clip. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicPasteResponse"];
                    };
                };
                /** @description Validation error, or paste folder not found / expired. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/clips/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload an image clip
         * @description Multipart upload of an image (png, jpg, jpeg, gif, bmp, webp), max 5 MB. Work in progress.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        content: string;
                        title?: string;
                        /** @default clipboard */
                        folder?: string;
                    };
                };
            };
            responses: {
                /** @description Uploaded. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadImageResponse"];
                    };
                };
                /** @description Invalid file or folder. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid `oc_token`. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/clips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List clips in the default folder
         * @description Same as `/client/v1/clips/{folder}` with `folder` = `clipboard`.
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    perPage?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Clips, newest first. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClipsListResponse"];
                    };
                };
                /** @description Missing or invalid `oc_token`. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/clips/{folder}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List clips in a folder */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    perPage?: number;
                };
                header?: never;
                path: {
                    /** @description Folder slug. */
                    folder: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Clips, newest first. `info` warns when an encrypted folder has no password yet. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClipsListResponse"];
                    };
                };
                /** @description Missing or invalid `oc_token`. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Folder not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/clips/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy clips into another folder (Pro)
         * @description Copies up to 100 clips into a folder. Requires an active Pro subscription.
         *
         *     - The target folder must belong to the user and must not be encrypted.
         *     - Clips in encrypted folders are skipped (`encrypted`).
         *     - Clips already in the target folder are skipped (`same_folder`).
         *     - If the target already holds a clip with identical content it is merged:
         *       the existing clip is touched instead of creating a duplicate.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "ids": [
                     *         "AMtJUhUOdQRACyd7wyiq3"
                     *       ],
                     *       "folder": "work"
                     *     }
                     */
                    "application/json": components["schemas"]["TransferClipsBody"];
                };
            };
            responses: {
                /** @description Per-clip results. Skipped ids do not fail the request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CopyClipsResponse"];
                    };
                };
                /** @description Validation error, unknown folder, or encrypted target folder. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not a Pro user. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/clips/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move clips into another folder
         * @description Moves up to 100 clips into a folder.
         *
         *     - The target folder must belong to the user and must not be encrypted.
         *     - Clips in encrypted folders are skipped (`encrypted`).
         *     - Clips already in the target folder are skipped (`same_folder`).
         *     - If the target already holds a clip with identical content it is merged:
         *       the existing clip is touched and the source clip is deleted.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "ids": [
                     *         "AMtJUhUOdQRACyd7wyiq3",
                     *         "oipWNu2PQkyhVq9ztZ2tV"
                     *       ],
                     *       "folder": "work"
                     *     }
                     */
                    "application/json": components["schemas"]["TransferClipsBody"];
                };
            };
            responses: {
                /** @description Per-clip results. Skipped ids do not fail the request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MoveClipsResponse"];
                    };
                };
                /** @description Validation error, unknown folder, or encrypted target folder. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/clips/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search clips
         * @description Case-insensitive substring search across the user's clips.
         *     `title` is searched on every clip; `content` only on clips that are not
         *     encrypted, because encrypted content is ciphertext.
         */
        get: {
            parameters: {
                query: {
                    /** @description Text to search for. Treated literally, not as a regex. */
                    q: string;
                    /** @description Restrict results to this folder slug. */
                    folder?: string;
                    page?: number;
                    perPage?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matching clips, newest first. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchClipsResponse"];
                    };
                };
                /** @description Missing or too long `q`. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/clip/{clip}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update a clip (Pro)
         * @description Only `title` and `content` can be changed. Requires an active Pro subscription.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Clip publicId. */
                    clip: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "title": "New title"
                     *     }
                     */
                    "application/json": components["schemas"]["UpdateClipBody"];
                };
            };
            responses: {
                /** @description Updated, or `info` when nothing changed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
                /** @description Validation error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not a Pro user. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clip not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/clip/{clip}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete a clip
         * @description Encrypted clips require the MD5 hash of their folder password in the body.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Clip publicId. */
                    clip: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DeleteClipBody"];
                };
            };
            responses: {
                /** @description Deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
                /** @description Wrong folder password. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clip not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/v1/account/set-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set plan
         * @description Sets the user's plan. Choosing `pro` creates a 7 day trial subscription.
         *     Paid Pro time is bought through `/client/v1/account/subscribe`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "plan": "pro"
                     *     }
                     */
                    "application/json": components["schemas"]["SetPlanBody"];
                };
            };
            responses: {
                /** @description Plan updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
                /** @description Validation error or plan already set. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid `oc_token`. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Standard error body. */
        ErrorResponse: {
            /** @description Human readable error message. */
            error: string;
            /** @description Name of the request field that failed validation, when applicable. */
            field?: string;
        };
        /** @description Simple message body. */
        MessageResponse: {
            message: string;
        };
        /** @description Public view of a subscription. */
        Subscription: components["schemas"]["SubStat"];
        SubStat: {
            publicId: string;
            /** @constant */
            plan: "pro";
            /** @enum {string} */
            type: "trial" | "monthly" | "yearly";
            /** @enum {string} */
            status: "pending" | "active" | "cancelled";
            amount: number;
            duration: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            expired: boolean;
            invoice?: {
                /** @constant */
                provider: "nowpayments";
                id: string;
                url?: string;
                status: components["schemas"]["InvoiceStatus"];
                /** Format: date-time */
                updatedAt?: string;
            };
        };
        /**
         * @description NowPayments payment statuses plus our own `pending` (invoice created, no payment started yet). See https://documenter.getpostman.com/view/7907941/2s93JusNJt#payment-statuses
         * @enum {string}
         */
        InvoiceStatus: "pending" | "waiting" | "confirming" | "confirmed" | "sending" | "partially_paid" | "finished" | "failed" | "refunded" | "expired";
        SubscribeBody: {
            /** @constant */
            plan: "pro";
            /**
             * @description Billing period.
             * @enum {string}
             */
            type: "monthly" | "yearly";
            /** @description Number of months or years, 1 to 5. */
            duration: number;
        };
        SubscribeResponse: {
            subscription: components["schemas"]["Subscription"];
            /** @description Hosted invoice to redirect the user to. */
            invoice?: {
                /** @constant */
                provider: "nowpayments";
                id: string;
                url?: string;
                status: components["schemas"]["InvoiceStatus"];
                /** Format: date-time */
                updatedAt?: string;
            };
            message: string;
        };
        SubscriptionStatusResponse: {
            /** @description Latest active subscription. May be expired, check `expired`. */
            subscription: components["schemas"]["Subscription"] | null;
            /** @description Pending (unpaid) subscriptions with their invoices, newest first. */
            pending: components["schemas"]["Subscription"][];
        };
        CancelSubscriptionBody: {
            /** @description `publicId` of a pending subscription. */
            subscription: string;
        };
        CancelSubscriptionResponse: {
            subscription: components["schemas"]["Subscription"];
            message: string;
        };
        /** @description Public view of a clip. */
        Clip: {
            publicId: string;
            title?: string;
            /** @enum {string} */
            type: "text" | "url" | "html" | "image";
            /** @description Slug of the folder the clip is in. */
            folder: string;
            /** @description The clip content. Ciphertext when `encrypted` is true. */
            context: string;
            locked?: boolean | null;
            favorite?: boolean | null;
            encrypted?: boolean | null;
            updatedAt?: string;
        };
        PaginatedClips: {
            page: number;
            perPage: number;
            total: number;
            lastPage: number;
            data: components["schemas"]["Clip"][];
        };
        SearchClipsResponse: {
            clips: components["schemas"]["PaginatedClips"];
            /** @description The trimmed search query that was used. */
            query: string;
        };
        TransferClipsBody: {
            /** @description `publicId`s of the clips to copy or move, 1 to 100. */
            ids: string[];
            /** @description Target folder name or slug. Must not be an encrypted folder. */
            folder: string;
        };
        /** @enum {string} */
        TransferSkipReason: "not_found" | "encrypted" | "same_folder";
        TransferSkipped: {
            id: string;
            reason: components["schemas"]["TransferSkipReason"];
        };
        MoveClipsResponse: {
            /** @description Slug of the target folder. */
            folder: string;
            /** @description Clips moved. */
            moved: {
                id: string;
            }[];
            /** @description Clips that already existed in the target: the existing clip was touched and the source deleted. */
            merged: string[];
            skipped: components["schemas"]["TransferSkipped"][];
            message: string;
        };
        CopyClipsResponse: {
            /** @description Slug of the target folder. */
            folder: string;
            /** @description Clips copied, with the `publicId` of each new copy. */
            copied: {
                id: string;
                copyId: string;
            }[];
            /** @description Clips that already existed in the target: the existing clip was touched. */
            merged: string[];
            skipped: components["schemas"]["TransferSkipped"][];
            message: string;
        };
        /** @description Public view of the authenticated user. */
        AuthUser: {
            username: string;
            publicId: string;
            email?: string;
            joinedAt: string;
            /** @enum {string|null} */
            plan?: "free" | "pro" | null;
        };
        PingResponse: {
            user: components["schemas"]["AuthUser"] | null;
            /** @description Latest active subscription, if any. */
            subscription?: components["schemas"]["Subscription"];
        };
        LoginBody: {
            /** @description 3 to 250 alphanumeric characters. */
            username: string;
            /** @description 6 to 500 characters. */
            password: string;
        };
        LoginResponse: {
            /** @description JWT to send in the `oc_token` header. */
            token: string;
            /** @enum {string|null} */
            plan: "free" | "pro" | null;
        };
        SignupBody: components["schemas"]["LoginBody"];
        CheckUsernameBody: {
            username: string;
        };
        CheckUsernameResponse: {
            /** @description Whether the username is already taken. */
            exists: boolean;
        };
        SetPlanBody: {
            /**
             * @description Choosing `pro` for the first time starts a 7 day trial.
             * @enum {string}
             */
            plan: "free" | "pro";
        };
        /** @description Public view of a folder. */
        Folder: {
            name: string;
            slug: string;
            /** @description Number of clips in the folder. Only present in the folder list. */
            contents?: number;
            /** @enum {string} */
            visibility: "public" | "private" | "encrypted";
            hasPassword?: boolean | null;
            /** @description Present when public paste is enabled. */
            publicPaste?: {
                id: string;
                date: string;
            };
        };
        CreateFolderBody: {
            /** @description Folder name, must be unique per user. The slug is derived from it. */
            name: string;
        };
        FolderPasswordBody: {
            /** @description MD5 hash (32 hex characters) of the password chosen by the user. */
            password: string;
        };
        CheckFolderPasswordResponse: {
            match: boolean;
        };
        PublicFolderResponse: {
            folder: components["schemas"]["Folder"];
        };
        PasteBody: {
            title?: string;
            content: string;
            /** @description Target folder name or slug. Defaults to `clipboard`. */
            folder?: string;
        };
        PasteResponse: {
            clip: components["schemas"]["Clip"];
        };
        PublicPasteBody: {
            title?: string;
            content: string;
        };
        PublicPasteResponse: {
            clip: components["schemas"]["Clip"];
            /** @description Present when a new clip was created. */
            message?: string;
            /** @description Present when identical content already existed and was only touched. */
            info?: string;
        };
        FindClipsBody: {
            /** @description `publicId`s of clips that were created through public paste. */
            ids: string[];
        };
        FindClipsResponse: {
            clips: components["schemas"]["PaginatedClips"];
        };
        ClipsListResponse: {
            clips: components["schemas"]["PaginatedClips"];
            /** @description Warning, e.g. the encrypted folder has no password set yet. */
            info?: string;
        };
        UpdateClipBody: {
            title?: string;
            content?: string;
        };
        DeleteClipBody: {
            /** @description Required only for encrypted clips: MD5 hash of the folder password. */
            password?: string;
        };
        UploadImageResponse: {
            message: string;
            /** @description Raw upload result. */
            content: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
